{% set name = "google-ads" %}
{% set version = "23.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # Use GH for upstream tests
  url: https://github.com/googleads/google-ads-python/archive/refs/tags/{{ version }}.tar.gz
  sha256: 5ebf11c13f4761b5f73eb39187c2d41eee2d81334936c3a646be41b2112ad9c8

build:
  number: 0
  skip: True                            # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - google-auth-oauthlib >=0.3.0,<2.0.0
    - google-api-core >=2.13.0,<=3.0.0
    - googleapis-common-protos >=1.56.3,<2.0.0
    - grpcio >=1.59.0,<2.0.0
    - grpcio-status >=1.59.0,<2.0.0
    - proto-plus >=1.22.3,<2.0.0
    - pyyaml >=5.1,<7.0
    - protobuf >=4.25.0,<5.0.0

test:
  imports:
    - google
    - google.ads
  commands:
    - rm tests/config_test.py tests/client_test.py
    - pip check
    - python -m unittest discover --buffer -s tests -p "*_test.py"
  requires:
    - pip
    - python
  source_files:
    - tests

about:
  home: https://github.com/googleads/google-ads-python
  summary: Client library for the Google Ads API
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  description: This project hosts the Python client library for the Google Ads API.
  dev_url: https://github.com/googleads/google-ads-python
  doc_url: https://developers.google.com/google-ads/api/docs/start

extra:
  recipe-maintainers:
    - xylar
