{% set name = "google-ads" %}
{% set version = "14.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-ads-{{ version }}.tar.gz
  sha256: 1682c0346a4adeb4afc56d88606ec76881d13a607cf885a5a8247d79bbb735f6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - google-api-core >=2.0.1,<3.0.0
    - google-auth-oauthlib >=0.3.0,<1.0.0"
    - googleapis-common-protos 1.5.8,<2.0.0
    - grpcio >=1.38.1,<2.0.0
    - nox >=2020.12.31,<2022.6
    - protobuf >=3.12.0,<3.18.0
    - pyyaml >=5.1,<6.0
    - setuptools >=40.3.0

test:
  imports:
    - google
    - google.ads
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleads/google-ads-python
  summary: Client library for the Google Ads API
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/googleads/google-ads-python
  doc_url: https://developers.google.com/google-ads/api/docs/start

extra:
  recipe-maintainers:
    - xylar
