{% set name = "google-ads" %}
{% set version = "9.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-ads-{{ version }}.tar.gz
  sha256: 75109496c0a4546d6312b560d75db0e80b66cce8a895dcd18e765ee831da3176

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - google-api-core >=1.14.0,<2.0.0
    - google-auth-oauthlib >=0.3.0,<1.0.0
    - googleapis-common-protos >=1.5.8,<2.0.0
    - grpcio >=1.25.0,<2.0.0
    - protobuf >=3.13.0,<4.0.0
    - python >=3.7
    - pyyaml >=5.1,<6.0
    - setuptools >=40.3.0

test:
  imports:
    - google
    - google.ads
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleads/google-ads-python
  summary: Client library for the Google Ads API
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/googleads/google-ads-python
  doc_url: https://developers.google.com/google-ads/api/docs/start

extra:
  recipe-maintainers:
    - xylar
